version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    branch: {{ env "PLATFORM_BRANCH" }}
    environment: {{ env "PLATFORM_ENVIRONMENT" }}
    project: {{ env "PLATFORM_PROJECT" }}
    service: {{ env "PLATFORM_APPLICATION_NAME" }}
    tree_id: {{ env "PLATFORM_TREE_ID" }}
storage:
  filesystem:
    rootdirectory: {{ env "PLATFORM_DIR" }}/var/lib/registry
auth:
  token:
{{- with json (slice (route "$[?(@.upstream == 'auth')]") "$[0].url") }}
    realm: {{ printf "%s://%s%s" .Scheme .Host .Path }}
{{- end }}
    service: Docker Registry
    issuer: Acme Auth Server
    rootcertbundle: {{ env "PLATFORM_DIR" }}/bundle.crt
http:
  addr: localhost:{{ env "PORT" }}
  net: tcp
  prefix: /
{{- with json (slice (route "$[?(@.upstream == 'registry')]") "$[0].url") }}
  host: {{ printf "%s://%s" .Scheme .Host }}
{{- end }}
  secret: {{ env "PLATFORM_PROJECT_ENTROPY" }}
redis:
{{- with json (rel "$.cache[0]") }}
  addr: {{ printf "%v:%v" .host .port }}
  db: 0
{{- with .password }}
  password: {{ . }}
{{- end }}
{{- end }}
